using ShadUI;
using Window = ShadUI.Window;

namespace Everywhere.Views;

public partial class TransientWindow : Window, IReactiveHost
{
    // Fields are now auto-generated by Avalonia NameGenerator
    public DialogHost DialogHost => PART_DialogHost;
    public ToastHost ToastHost => PART_ToastHost;

    public TransientWindow()
    {
        InitializeComponent();
    }

    private void InitializeComponent()
    {
        Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(this);
    }

    protected override void OnClosed(EventArgs e)
    {
        // Its content should be null before closing to make it detach from the visual tree.
        // Otherwise, it will try to attach to the visual tree again (Exception).
        Content = null;
        base.OnClosed(e);
    }
}